### PR TITLE
fix: fixed hard dependency of Buffer on the global object

### LINKED ISSUE #69: Remove `Buffer` dependency
Great package! Unfortunately the global `Buffer` dependency is causing issues when bundling for frontend. It looks like only one method is used, it should be relatively straightforward to replace that dependency with something minimal.

### PR DESCRIPTION
**Pull request by tonfido**
Fixes #69

### CODE REVIEW

**Review by alexgorbatchev — APPROVED** [review]

**Comment by tonfido** [comment]
@RossWilliams, would you mind taking a look.

**Comment by alexgorbatchev** [comment]
Ping

**Comment by tonfido** [comment]
@RossWilliams please take a look on the PR.

**Comment by tonfido** [comment]
Orphaned?

**Comment by tonfido** [comment]
Orphaned?

**Review by RossWilliams — APPROVED** [review]

**Pull request merged**
